spring.application.name=progreso2-integracion-granja-jonathan
server.port=8080

camel.springboot.main-run-controller=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.edu.udla.integracion.progreso2=INFO
